export const backgroundJson = {
	products: [
		{
			id: 1,
			nome: "Produto 1",
			preco: 577.38,
			descricao: "Descrição do Produto 1",
			categoria: "Eletrônicos",
			estoque: 47,
		},
		{
			id: 2,
			nome: "Produto 2",
			preco: 127.26,
			descricao: "Descrição do Produto 2",
			categoria: "Esportes",
			estoque: 21,
		},
		{
			id: 3,
			nome: "Produto 3",
			preco: 401.21,
			descricao: "Descrição do Produto 3",
			categoria: "Moda",
			estoque: 80,
		},
		{
			id: 4,
			nome: "Produto 4",
			preco: 739.81,
			descricao: "Descrição do Produto 4",
			categoria: "Casa",
			estoque: 50,
		},
		{
			id: 5,
			nome: "Produto 5",
			preco: 943.02,
			descricao: "Descrição do Produto 5",
			categoria: "Casa",
			estoque: 81,
		},
		{
			id: 6,
			nome: "Produto 6",
			preco: 352.57,
			descricao: "Descrição do Produto 6",
			categoria: "Eletrônicos",
			estoque: 53,
		},
		{
			id: 7,
			nome: "Produto 7",
			preco: 238.65,
			descricao: "Descrição do Produto 7",
			categoria: "Moda",
			estoque: 82,
		},
		{
			id: 8,
			nome: "Produto 8",
			preco: 512.52,
			descricao: "Descrição do Produto 8",
			categoria: "Moda",
			estoque: 68,
		},
		{
			id: 9,
			nome: "Produto 9",
			preco: 625.53,
			descricao: "Descrição do Produto 9",
			categoria: "Moda",
			estoque: 52,
		},
		{
			id: 10,
			nome: "Produto 10",
			preco: 760.98,
			descricao: "Descrição do Produto 10",
			categoria: "Livros",
			estoque: 24,
		},
		{
			id: 11,
			nome: "Produto 11",
			preco: 865.04,
			descricao: "Descrição do Produto 11",
			categoria: "Eletrônicos",
			estoque: 25,
		},
		{
			id: 12,
			nome: "Produto 12",
			preco: 675.79,
			descricao: "Descrição do Produto 12",
			categoria: "Livros",
			estoque: 91,
		},
		{
			id: 13,
			nome: "Produto 13",
			preco: 524.77,
			descricao: "Descrição do Produto 13",
			categoria: "Moda",
			estoque: 73,
		},
		{
			id: 14,
			nome: "Produto 14",
			preco: 656.36,
			descricao: "Descrição do Produto 14",
			categoria: "Moda",
			estoque: 41,
		},
		{
			id: 15,
			nome: "Produto 15",
			preco: 291.38,
			descricao: "Descrição do Produto 15",
			categoria: "Moda",
			estoque: 18,
		},
		{
			id: 16,
			nome: "Produto 16",
			preco: 272.8,
			descricao: "Descrição do Produto 16",
			categoria: "Casa",
			estoque: 86,
		},
		{
			id: 17,
			nome: "Produto 17",
			preco: 833.75,
			descricao: "Descrição do Produto 17",
			categoria: "Livros",
			estoque: 89,
		},
		{
			id: 18,
			nome: "Produto 18",
			preco: 179.52,
			descricao: "Descrição do Produto 18",
			categoria: "Casa",
			estoque: 74,
		},
		{
			id: 19,
			nome: "Produto 19",
			preco: 598.78,
			descricao: "Descrição do Produto 19",
			categoria: "Moda",
			estoque: 8,
		},
		{
			id: 20,
			nome: "Produto 20",
			preco: 148.04,
			descricao: "Descrição do Produto 20",
			categoria: "Livros",
			estoque: 63,
		},
		{
			id: 21,
			nome: "Produto 21",
			preco: 738.07,
			descricao: "Descrição do Produto 21",
			categoria: "Moda",
			estoque: 61,
		},
		{
			id: 22,
			nome: "Produto 22",
			preco: 150.22,
			descricao: "Descrição do Produto 22",
			categoria: "Moda",
			estoque: 93,
		},
		{
			id: 23,
			nome: "Produto 23",
			preco: 666.28,
			descricao: "Descrição do Produto 23",
			categoria: "Esportes",
			estoque: 98,
		},
		{
			id: 24,
			nome: "Produto 24",
			preco: 565.93,
			descricao: "Descrição do Produto 24",
			categoria: "Esportes",
			estoque: 85,
		},
		{
			id: 25,
			nome: "Produto 25",
			preco: 531.29,
			descricao: "Descrição do Produto 25",
			categoria: "Casa",
			estoque: 59,
		},
		{
			id: 26,
			nome: "Produto 26",
			preco: 940.55,
			descricao: "Descrição do Produto 26",
			categoria: "Casa",
			estoque: 3,
		},
		{
			id: 27,
			nome: "Produto 27",
			preco: 505.19,
			descricao: "Descrição do Produto 27",
			categoria: "Eletrônicos",
			estoque: 74,
		},
		{
			id: 28,
			nome: "Produto 28",
			preco: 687.69,
			descricao: "Descrição do Produto 28",
			categoria: "Eletrônicos",
			estoque: 26,
		},
		{
			id: 29,
			nome: "Produto 29",
			preco: 966.92,
			descricao: "Descrição do Produto 29",
			categoria: "Casa",
			estoque: 72,
		},
		{
			id: 30,
			nome: "Produto 30",
			preco: 767.95,
			descricao: "Descrição do Produto 30",
			categoria: "Esportes",
			estoque: 11,
		},
		{
			id: 31,
			nome: "Produto 31",
			preco: 974.3,
			descricao: "Descrição do Produto 31",
			categoria: "Livros",
			estoque: 24,
		},
		{
			id: 32,
			nome: "Produto 32",
			preco: 513.17,
			descricao: "Descrição do Produto 32",
			categoria: "Eletrônicos",
			estoque: 96,
		},
		{
			id: 33,
			nome: "Produto 33",
			preco: 275.34,
			descricao: "Descrição do Produto 33",
			categoria: "Eletrônicos",
			estoque: 34,
		},
		{
			id: 34,
			nome: "Produto 34",
			preco: 805.27,
			descricao: "Descrição do Produto 34",
			categoria: "Casa",
			estoque: 94,
		},
		{
			id: 35,
			nome: "Produto 35",
			preco: 720.88,
			descricao: "Descrição do Produto 35",
			categoria: "Casa",
			estoque: 57,
		},
		{
			id: 36,
			nome: "Produto 36",
			preco: 879.12,
			descricao: "Descrição do Produto 36",
			categoria: "Esportes",
			estoque: 10,
		},
		{
			id: 37,
			nome: "Produto 37",
			preco: 666.96,
			descricao: "Descrição do Produto 37",
			categoria: "Casa",
			estoque: 37,
		},
		{
			id: 38,
			nome: "Produto 38",
			preco: 993.03,
			descricao: "Descrição do Produto 38",
			categoria: "Moda",
			estoque: 64,
		},
		{
			id: 39,
			nome: "Produto 39",
			preco: 198.86,
			descricao: "Descrição do Produto 39",
			categoria: "Moda",
			estoque: 75,
		},
		{
			id: 40,
			nome: "Produto 40",
			preco: 513.36,
			descricao: "Descrição do Produto 40",
			categoria: "Esportes",
			estoque: 45,
		},
		{
			id: 41,
			nome: "Produto 41",
			preco: 331.11,
			descricao: "Descrição do Produto 41",
			categoria: "Esportes",
			estoque: 65,
		},
		{
			id: 42,
			nome: "Produto 42",
			preco: 795.47,
			descricao: "Descrição do Produto 42",
			categoria: "Casa",
			estoque: 67,
		},
		{
			id: 43,
			nome: "Produto 43",
			preco: 956.37,
			descricao: "Descrição do Produto 43",
			categoria: "Esportes",
			estoque: 63,
		},
		{
			id: 44,
			nome: "Produto 44",
			preco: 130.9,
			descricao: "Descrição do Produto 44",
			categoria: "Casa",
			estoque: 60,
		},
		{
			id: 45,
			nome: "Produto 45",
			preco: 765.49,
			descricao: "Descrição do Produto 45",
			categoria: "Livros",
			estoque: 25,
		},
		{
			id: 46,
			nome: "Produto 46",
			preco: 970.94,
			descricao: "Descrição do Produto 46",
			categoria: "Eletrônicos",
			estoque: 10,
		},
		{
			id: 47,
			nome: "Produto 47",
			preco: 841.9,
			descricao: "Descrição do Produto 47",
			categoria: "Moda",
			estoque: 72,
		},
		{
			id: 48,
			nome: "Produto 48",
			preco: 615.3,
			descricao: "Descrição do Produto 48",
			categoria: "Livros",
			estoque: 35,
		},
		{
			id: 49,
			nome: "Produto 49",
			preco: 994.08,
			descricao: "Descrição do Produto 49",
			categoria: "Casa",
			estoque: 66,
		},
		{
			id: 50,
			nome: "Produto 50",
			preco: 750.25,
			descricao: "Descrição do Produto 50",
			categoria: "Livros",
			estoque: 87,
		},
	],
};

export const foregroundForeground = {
	transactions: [
		{
			id: 1,
			marca: "Honda",
			modelo: "SUV",
			ano: 2010,
			cor: "Branco",
			preco: 80695.6,
			data_venda: "11/01/2023",
			comprador: "Cliente 1",
			vendedor: "Vendedor 3",
			local_venda: "Belo Horizonte",
		},
		{
			id: 2,
			marca: "Chevrolet",
			modelo: "Caminhonete",
			ano: 2020,
			cor: "Azul",
			preco: 58963.89,
			data_venda: "13/09/2023",
			comprador: "Cliente 2",
			vendedor: "Vendedor 6",
			local_venda: "Salvador",
		},
		{
			id: 3,
			marca: "Honda",
			modelo: "Convers\u00edvel",
			ano: 2012,
			cor: "Branco",
			preco: 43075.33,
			data_venda: "01/10/2023",
			comprador: "Cliente 3",
			vendedor: "Vendedor 4",
			local_venda: "Curitiba",
		},
		{
			id: 4,
			marca: "Honda",
			modelo: "Caminhonete",
			ano: 2023,
			cor: "Preto",
			preco: 23782.66,
			data_venda: "25/06/2023",
			comprador: "Cliente 4",
			vendedor: "Vendedor 5",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 5,
			marca: "Honda",
			modelo: "Hatchback",
			ano: 2011,
			cor: "Vermelho",
			preco: 34746.53,
			data_venda: "06/01/2023",
			comprador: "Cliente 5",
			vendedor: "Vendedor 9",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 6,
			marca: "Volkswagen",
			modelo: "SUV",
			ano: 2007,
			cor: "Vermelho",
			preco: 50161.17,
			data_venda: "17/12/2023",
			comprador: "Cliente 6",
			vendedor: "Vendedor 1",
			local_venda: "Curitiba",
		},
		{
			id: 7,
			marca: "Chevrolet",
			modelo: "Hatchback",
			ano: 2016,
			cor: "Prata",
			preco: 125733.12,
			data_venda: "15/02/2023",
			comprador: "Cliente 7",
			vendedor: "Vendedor 8",
			local_venda: "Curitiba",
		},
		{
			id: 8,
			marca: "Chevrolet",
			modelo: "Convers\u00edvel",
			ano: 2011,
			cor: "Branco",
			preco: 106261.83,
			data_venda: "19/09/2023",
			comprador: "Cliente 8",
			vendedor: "Vendedor 6",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 9,
			marca: "Ford",
			modelo: "SUV",
			ano: 2007,
			cor: "Branco",
			preco: 119191.55,
			data_venda: "15/09/2023",
			comprador: "Cliente 9",
			vendedor: "Vendedor 9",
			local_venda: "Belo Horizonte",
		},
		{
			id: 10,
			marca: "Ford",
			modelo: "Caminhonete",
			ano: 2005,
			cor: "Vermelho",
			preco: 47643.01,
			data_venda: "04/12/2023",
			comprador: "Cliente 10",
			vendedor: "Vendedor 4",
			local_venda: "Salvador",
		},
		{
			id: 11,
			marca: "Volkswagen",
			modelo: "Sedan",
			ano: 2019,
			cor: "Vermelho",
			preco: 96708.12,
			data_venda: "21/06/2023",
			comprador: "Cliente 11",
			vendedor: "Vendedor 5",
			local_venda: "Salvador",
		},
		{
			id: 12,
			marca: "BMW",
			modelo: "Caminhonete",
			ano: 2022,
			cor: "Vermelho",
			preco: 113729.01,
			data_venda: "12/04/2023",
			comprador: "Cliente 12",
			vendedor: "Vendedor 9",
			local_venda: "Salvador",
		},
		{
			id: 13,
			marca: "Toyota",
			modelo: "SUV",
			ano: 2007,
			cor: "Branco",
			preco: 68471.83,
			data_venda: "22/08/2023",
			comprador: "Cliente 13",
			vendedor: "Vendedor 10",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 14,
			marca: "Honda",
			modelo: "Sedan",
			ano: 2005,
			cor: "Prata",
			preco: 118749.67,
			data_venda: "02/05/2023",
			comprador: "Cliente 14",
			vendedor: "Vendedor 9",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 15,
			marca: "Nissan",
			modelo: "Convers\u00edvel",
			ano: 2011,
			cor: "Prata",
			preco: 21918.65,
			data_venda: "16/04/2023",
			comprador: "Cliente 15",
			vendedor: "Vendedor 2",
			local_venda: "Curitiba",
		},
		{
			id: 16,
			marca: "Jeep",
			modelo: "Sedan",
			ano: 2016,
			cor: "Branco",
			preco: 113157.42,
			data_venda: "21/04/2023",
			comprador: "Cliente 16",
			vendedor: "Vendedor 10",
			local_venda: "Belo Horizonte",
		},
		{
			id: 17,
			marca: "Toyota",
			modelo: "Sedan",
			ano: 2018,
			cor: "Azul",
			preco: 118913.29,
			data_venda: "17/11/2023",
			comprador: "Cliente 17",
			vendedor: "Vendedor 10",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 18,
			marca: "BMW",
			modelo: "Convers\u00edvel",
			ano: 2015,
			cor: "Branco",
			preco: 117779.22,
			data_venda: "28/04/2023",
			comprador: "Cliente 18",
			vendedor: "Vendedor 4",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 19,
			marca: "Mercedes-Benz",
			modelo: "Convers\u00edvel",
			ano: 2023,
			cor: "Vermelho",
			preco: 32408.47,
			data_venda: "17/05/2023",
			comprador: "Cliente 19",
			vendedor: "Vendedor 8",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 20,
			marca: "Volkswagen",
			modelo: "SUV",
			ano: 2006,
			cor: "Cinza",
			preco: 85367.14,
			data_venda: "03/03/2023",
			comprador: "Cliente 20",
			vendedor: "Vendedor 6",
			local_venda: "Belo Horizonte",
		},
		{
			id: 21,
			marca: "Nissan",
			modelo: "Caminhonete",
			ano: 2022,
			cor: "Preto",
			preco: 103247.71,
			data_venda: "17/09/2023",
			comprador: "Cliente 21",
			vendedor: "Vendedor 2",
			local_venda: "Belo Horizonte",
		},
		{
			id: 22,
			marca: "Ford",
			modelo: "SUV",
			ano: 2020,
			cor: "Branco",
			preco: 115200.14,
			data_venda: "02/02/2023",
			comprador: "Cliente 22",
			vendedor: "Vendedor 2",
			local_venda: "Curitiba",
		},
		{
			id: 23,
			marca: "BMW",
			modelo: "Sedan",
			ano: 2006,
			cor: "Preto",
			preco: 143799.62,
			data_venda: "02/02/2023",
			comprador: "Cliente 23",
			vendedor: "Vendedor 1",
			local_venda: "Curitiba",
		},
		{
			id: 24,
			marca: "Chevrolet",
			modelo: "SUV",
			ano: 2006,
			cor: "Prata",
			preco: 107649.9,
			data_venda: "06/09/2023",
			comprador: "Cliente 24",
			vendedor: "Vendedor 7",
			local_venda: "Curitiba",
		},
		{
			id: 25,
			marca: "Volkswagen",
			modelo: "Sedan",
			ano: 2020,
			cor: "Azul",
			preco: 149590.04,
			data_venda: "05/02/2023",
			comprador: "Cliente 25",
			vendedor: "Vendedor 5",
			local_venda: "Salvador",
		},
		{
			id: 26,
			marca: "Chevrolet",
			modelo: "Caminhonete",
			ano: 2008,
			cor: "Cinza",
			preco: 64860.38,
			data_venda: "09/02/2023",
			comprador: "Cliente 26",
			vendedor: "Vendedor 6",
			local_venda: "Curitiba",
		},
		{
			id: 27,
			marca: "Volkswagen",
			modelo: "Convers\u00edvel",
			ano: 2013,
			cor: "Prata",
			preco: 52623.74,
			data_venda: "03/03/2023",
			comprador: "Cliente 27",
			vendedor: "Vendedor 10",
			local_venda: "Curitiba",
		},
		{
			id: 28,
			marca: "Ford",
			modelo: "Caminhonete",
			ano: 2016,
			cor: "Azul",
			preco: 100358.33,
			data_venda: "09/11/2023",
			comprador: "Cliente 28",
			vendedor: "Vendedor 10",
			local_venda: "Curitiba",
		},
		{
			id: 29,
			marca: "Honda",
			modelo: "Caminhonete",
			ano: 2023,
			cor: "Prata",
			preco: 34007.93,
			data_venda: "22/01/2023",
			comprador: "Cliente 29",
			vendedor: "Vendedor 5",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 30,
			marca: "BMW",
			modelo: "Hatchback",
			ano: 2015,
			cor: "Preto",
			preco: 31342.14,
			data_venda: "18/05/2023",
			comprador: "Cliente 30",
			vendedor: "Vendedor 8",
			local_venda: "Salvador",
		},
		{
			id: 31,
			marca: "Audi",
			modelo: "Caminhonete",
			ano: 2014,
			cor: "Prata",
			preco: 47878.02,
			data_venda: "01/03/2023",
			comprador: "Cliente 31",
			vendedor: "Vendedor 4",
			local_venda: "Belo Horizonte",
		},
		{
			id: 32,
			marca: "Nissan",
			modelo: "Convers\u00edvel",
			ano: 2014,
			cor: "Azul",
			preco: 148587.17,
			data_venda: "12/01/2023",
			comprador: "Cliente 32",
			vendedor: "Vendedor 8",
			local_venda: "Belo Horizonte",
		},
		{
			id: 33,
			marca: "Toyota",
			modelo: "Hatchback",
			ano: 2010,
			cor: "Cinza",
			preco: 90608.72,
			data_venda: "08/04/2023",
			comprador: "Cliente 33",
			vendedor: "Vendedor 2",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 34,
			marca: "Mercedes-Benz",
			modelo: "Hatchback",
			ano: 2016,
			cor: "Azul",
			preco: 53283.51,
			data_venda: "05/11/2023",
			comprador: "Cliente 34",
			vendedor: "Vendedor 9",
			local_venda: "Curitiba",
		},
		{
			id: 35,
			marca: "Volkswagen",
			modelo: "Caminhonete",
			ano: 2011,
			cor: "Prata",
			preco: 123034.74,
			data_venda: "26/01/2023",
			comprador: "Cliente 35",
			vendedor: "Vendedor 5",
			local_venda: "Salvador",
		},
		{
			id: 36,
			marca: "BMW",
			modelo: "Hatchback",
			ano: 2019,
			cor: "Azul",
			preco: 128548.57,
			data_venda: "01/05/2023",
			comprador: "Cliente 36",
			vendedor: "Vendedor 3",
			local_venda: "Belo Horizonte",
		},
		{
			id: 37,
			marca: "Toyota",
			modelo: "Sedan",
			ano: 2014,
			cor: "Prata",
			preco: 25970.06,
			data_venda: "10/06/2023",
			comprador: "Cliente 37",
			vendedor: "Vendedor 2",
			local_venda: "Belo Horizonte",
		},
		{
			id: 38,
			marca: "Toyota",
			modelo: "SUV",
			ano: 2012,
			cor: "Cinza",
			preco: 114486.76,
			data_venda: "04/11/2023",
			comprador: "Cliente 38",
			vendedor: "Vendedor 5",
			local_venda: "Salvador",
		},
		{
			id: 39,
			marca: "Volkswagen",
			modelo: "Hatchback",
			ano: 2009,
			cor: "Branco",
			preco: 82601.93,
			data_venda: "09/08/2023",
			comprador: "Cliente 39",
			vendedor: "Vendedor 8",
			local_venda: "Belo Horizonte",
		},
		{
			id: 40,
			marca: "Audi",
			modelo: "Sedan",
			ano: 2009,
			cor: "Azul",
			preco: 46141.38,
			data_venda: "12/02/2023",
			comprador: "Cliente 40",
			vendedor: "Vendedor 8",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 41,
			marca: "Nissan",
			modelo: "Caminhonete",
			ano: 2011,
			cor: "Prata",
			preco: 121735.38,
			data_venda: "08/06/2023",
			comprador: "Cliente 41",
			vendedor: "Vendedor 4",
			local_venda: "Belo Horizonte",
		},
		{
			id: 42,
			marca: "Chevrolet",
			modelo: "Caminhonete",
			ano: 2005,
			cor: "Azul",
			preco: 80024.84,
			data_venda: "20/10/2023",
			comprador: "Cliente 42",
			vendedor: "Vendedor 6",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 43,
			marca: "Chevrolet",
			modelo: "SUV",
			ano: 2019,
			cor: "Cinza",
			preco: 28629.82,
			data_venda: "28/02/2023",
			comprador: "Cliente 43",
			vendedor: "Vendedor 1",
			local_venda: "Salvador",
		},
		{
			id: 44,
			marca: "Nissan",
			modelo: "Hatchback",
			ano: 2023,
			cor: "Branco",
			preco: 106564.94,
			data_venda: "09/04/2023",
			comprador: "Cliente 44",
			vendedor: "Vendedor 8",
			local_venda: "Curitiba",
		},
		{
			id: 45,
			marca: "Mercedes-Benz",
			modelo: "Sedan",
			ano: 2013,
			cor: "Cinza",
			preco: 138118.88,
			data_venda: "26/11/2023",
			comprador: "Cliente 45",
			vendedor: "Vendedor 1",
			local_venda: "Belo Horizonte",
		},
		{
			id: 46,
			marca: "Honda",
			modelo: "Convers\u00edvel",
			ano: 2019,
			cor: "Cinza",
			preco: 114405.01,
			data_venda: "07/05/2023",
			comprador: "Cliente 46",
			vendedor: "Vendedor 9",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 47,
			marca: "Honda",
			modelo: "Sedan",
			ano: 2009,
			cor: "Branco",
			preco: 46866.27,
			data_venda: "06/03/2023",
			comprador: "Cliente 47",
			vendedor: "Vendedor 9",
			local_venda: "Rio de Janeiro",
		},
		{
			id: 48,
			marca: "BMW",
			modelo: "Convers\u00edvel",
			ano: 2006,
			cor: "Vermelho",
			preco: 106879.3,
			data_venda: "17/10/2023",
			comprador: "Cliente 48",
			vendedor: "Vendedor 5",
			local_venda: "S\u00e3o Paulo",
		},
		{
			id: 49,
			marca: "Chevrolet",
			modelo: "Caminhonete",
			ano: 2014,
			cor: "Vermelho",
			preco: 145376.7,
			data_venda: "07/10/2023",
			comprador: "Cliente 49",
			vendedor: "Vendedor 5",
			local_venda: "Salvador",
		},
		{
			id: 50,
			marca: "Jeep",
			modelo: "Convers\u00edvel",
			ano: 2018,
			cor: "Vermelho",
			preco: 134667.25,
			data_venda: "07/03/2023",
			comprador: "Cliente 50",
			vendedor: "Vendedor 5",
			local_venda: "Rio de Janeiro",
		},
	],
};
